CREATE TABLE IF NOT EXISTS `adm_par` (
  `firma` char(70) NOT NULL,
  `reg_adres` char(70) DEFAULT NULL,
  `reg_vieta` char(70) DEFAULT NULL,
  `reg_nr` char(100) DEFAULT NULL,
  `zurnalas` char(3) NOT NULL,
  `sandelis` char(5) DEFAULT NULL,
  `pvm_def` decimal(5,2) DEFAULT NULL,
  `kasa` char(12) DEFAULT NULL,
  `bankas` char(12) DEFAULT NULL,
  `darb_skola` char(12) DEFAULT NULL,
  `darb_ats` char(12) DEFAULT NULL,
  `paj_san` char(12) DEFAULT NULL,
  `likutis` char(12) DEFAULT NULL,
  `gav_pvm` char(12) DEFAULT NULL,
  `gav_skol` char(12) DEFAULT NULL,
  `gav_avans` char(12) DEFAULT NULL,
  `pardavimai` char(12) DEFAULT NULL,
  `pard_savik` char(12) DEFAULT NULL,
  `tiek_kaup` char(12) DEFAULT NULL,
  `tiek_pvm` char(12) DEFAULT NULL,
  `tiek_skol` char(12) DEFAULT NULL,
  `tiek_avans` char(12) DEFAULT NULL,
  `tran_deb` char(12) DEFAULT NULL,
  `tran_kred` char(12) DEFAULT NULL,
  `muit_deb` char(12) DEFAULT NULL,
  `muit_kred` char(12) DEFAULT NULL,
  `kitos_deb` char(12) DEFAULT NULL,
  `kitos_kred` char(12) DEFAULT NULL,
  `akciz_deb` char(12) DEFAULT NULL,
  `akciz_kred` char(12) DEFAULT NULL,
  `pradinis` char(12) DEFAULT NULL,
  `tarp_zurn` char(12) DEFAULT NULL,
  `apm_pardav` char(12) DEFAULT NULL,
  `apm_savik` char(12) DEFAULT NULL,
  `pard_graz` char(12) DEFAULT NULL,
  `uzskait` char(12) DEFAULT NULL,
  `apm_p_dt` date DEFAULT NULL,
  `prek_gap` date DEFAULT NULL,
  `fin_gap` date DEFAULT NULL,
  `du_gap` date DEFAULT NULL,
  `fin_edit` char(100) DEFAULT NULL,
  `mase` decimal(1,0) DEFAULT NULL,
  `demo_mode` char(30) DEFAULT NULL,
  `prec_sum` decimal(2,0) DEFAULT NULL,
  `prec_disc` decimal(2,0) DEFAULT NULL,
  `prec_vat` decimal(2,0) DEFAULT NULL,
  `kaina_1` char(60) DEFAULT NULL,
  `kaina_2` char(60) DEFAULT NULL,
  `kaina_3` char(60) DEFAULT NULL,
  `kaina_4` char(60) DEFAULT NULL,
  `kaina_5` char(60) DEFAULT NULL,
  `kaina_6` char(60) DEFAULT NULL,
  `kaina_7` char(60) DEFAULT NULL,
  `kaina_8` char(60) DEFAULT NULL,
  `kaina_9` char(60) DEFAULT NULL,
  `kaina_10` char(60) DEFAULT NULL,
  `kaina_11` char(60) DEFAULT NULL,
  `kaina_12` char(60) DEFAULT NULL,
  `kaina_13` char(60) DEFAULT NULL,
  `kaina_14` char(60) DEFAULT NULL,
  `kaina_15` char(60) DEFAULT NULL,
  `kaina_16` char(60) DEFAULT NULL,
  `kaina_17` char(60) DEFAULT NULL,
  `kaina_18` char(60) DEFAULT NULL,
  `kaina_19` char(60) DEFAULT NULL,
  `kaina_20` char(60) DEFAULT NULL,
  `k_user_1` char(100) DEFAULT NULL,
  `k_user_2` char(100) DEFAULT NULL,
  `k_user_3` char(100) DEFAULT NULL,
  `k_user_4` char(100) DEFAULT NULL,
  `k_user_5` char(100) DEFAULT NULL,
  `k_user_6` char(100) DEFAULT NULL,
  `k_user_7` char(100) DEFAULT NULL,
  `k_user_8` char(100) DEFAULT NULL,
  `k_user_9` char(100) DEFAULT NULL,
  `k_user_10` char(100) DEFAULT NULL,
  `k_user_11` char(100) DEFAULT NULL,
  `k_user_12` char(100) DEFAULT NULL,
  `k_user_13` char(100) DEFAULT NULL,
  `k_user_14` char(100) DEFAULT NULL,
  `k_user_15` char(100) DEFAULT NULL,
  `k_user_16` char(100) DEFAULT NULL,
  `k_user_17` char(100) DEFAULT NULL,
  `k_user_18` char(100) DEFAULT NULL,
  `k_user_19` char(100) DEFAULT NULL,
  `k_user_20` char(100) DEFAULT NULL,
  `def_turin` char(30) DEFAULT NULL,
  `upd_fin_md` decimal(1,0) DEFAULT NULL,
  `w_title` char(100) DEFAULT NULL,
  `kurs_teig` char(12) DEFAULT NULL,
  `kurs_neig` char(12) DEFAULT NULL,
  `kurs_pad` char(30) DEFAULT NULL,
  `kurs_veikl` char(30) DEFAULT NULL,
  `kurs_centr` char(30) DEFAULT NULL,
  `kurs_s_t` char(60) DEFAULT NULL,
  `kurs_s_n` char(60) DEFAULT NULL,
  `fin_perk_t` char(1) DEFAULT NULL,
  `min_preke` int(11) DEFAULT NULL,
  `max_preke` int(11) DEFAULT NULL,
  `unique_art` decimal(1,0) DEFAULT NULL,
  `build_date` date DEFAULT NULL,
  `licencija` char(100) DEFAULT NULL,
  `f_upd_data` date DEFAULT NULL,
  `pakr_punkt` char(100) DEFAULT NULL,
  `prek_atsak` char(100) DEFAULT NULL,
  `val_mode` decimal(1,0) DEFAULT NULL,
  `fin_time` decimal(1,0) DEFAULT NULL,
  `fin_exch` decimal(1,0) DEFAULT NULL,
  `prek_prop` text,
  `reg_start` datetime DEFAULT NULL,
  `min_id` int(11) DEFAULT NULL,
  `max_id` int(11) DEFAULT NULL,
  `view_ext` char(100) DEFAULT NULL,
  `modify_ext` char(100) DEFAULT NULL,
  `road_mode` decimal(1,0) DEFAULT NULL,
  `apm_gap` date DEFAULT NULL,
  `licence` char(100) DEFAULT NULL,
  `picture` char(30) DEFAULT NULL,
  `icon` char(30) DEFAULT NULL,
  `properties` text,
  `fin_prop` text,
  `gam_prop` text,
  `ats_prop` text,
  `du_prop` text,
  `anal_prop` text,
  `turt_prop` text,
  `sys_prop` text,
  `pers_prop` text,
  `prep_prop` text,
  `pos_prop` text,
  `uzs_prop` text,
  `blnk_prop` text,
  `mrp_prop` text,
  `vogon_prop` text,
  `min_date` date DEFAULT NULL,
  `max_date` date DEFAULT NULL,
  `nl_lst` char(50) DEFAULT NULL,
  `nl_dsc` decimal(1,0) DEFAULT NULL,
  `nl_qty` decimal(1,0) DEFAULT NULL,
  `nl_sum` decimal(1,0) DEFAULT NULL,
  `section` char(30) DEFAULT NULL,
  `adm_id` int(11) NOT NULL,
  `inp_time` datetime DEFAULT NULL,
  `inp_user` int(11) DEFAULT NULL,
  `mod_time` datetime DEFAULT NULL,
  `mod_user` int(11) DEFAULT NULL,
  `lock_time` datetime DEFAULT NULL,
  `lock_user` int(11) DEFAULT NULL,
  `print_time` datetime DEFAULT NULL,
  `print_user` int(11) DEFAULT NULL,
  PRIMARY KEY (`adm_id`)
) ENGINE=InnoDB DEFAULT CHARSET=cp1257 COLLATE=cp1257_lithuanian_ci;
